# Generated by Django 4.2.3 on 2023-07-31 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plate_found", models.BooleanField()),
                ("plate_country", models.CharField(max_length=3)),
                ("plate_type_confidence", models.IntegerField()),
                ("position_confidence", models.IntegerField()),
                ("plate_chars", models.JSONField()),
                ("unicode_text", models.CharField(max_length=50)),
                ("separated_text", models.CharField(max_length=50)),
                ("engine", models.CharField(max_length=50)),
                ("proctime", models.IntegerField()),
                ("confidence", models.IntegerField()),
                ("plate_roi", models.JSONField()),
                ("plate_type", models.IntegerField()),
                ("mmr_engine", models.CharField(max_length=50)),
                ("mmr_found", models.BooleanField()),
                ("mmr_proctime", models.IntegerField()),
                ("mmr_category", models.CharField(max_length=50)),
                ("mmr_category_confidence", models.IntegerField()),
                ("mmr_color", models.JSONField()),
                ("mmr_color_confidence", models.IntegerField()),
                ("mmr_make", models.CharField(max_length=50)),
                ("mmr_model", models.CharField(max_length=50)),
                ("mmr_make_confidence", models.IntegerField()),
                ("mmr_model_confidence", models.IntegerField()),
                ("mmr_heading", models.CharField(max_length=50)),
                ("mmr_heading_confidence", models.IntegerField()),
                ("bounds", models.JSONField()),
            ],
        ),
    ]
