# Generated by Django 4.2.3 on 2023-07-31 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vehicle", old_name="bounds", new_name="data",
        ),
        migrations.RemoveField(model_name="vehicle", name="confidence",),
        migrations.RemoveField(model_name="vehicle", name="engine",),
        migrations.RemoveField(model_name="vehicle", name="mmr_category",),
        migrations.RemoveField(model_name="vehicle", name="mmr_category_confidence",),
        migrations.RemoveField(model_name="vehicle", name="mmr_color",),
        migrations.RemoveField(model_name="vehicle", name="mmr_color_confidence",),
        migrations.RemoveField(model_name="vehicle", name="mmr_engine",),
        migrations.RemoveField(model_name="vehicle", name="mmr_found",),
        migrations.RemoveField(model_name="vehicle", name="mmr_heading",),
        migrations.RemoveField(model_name="vehicle", name="mmr_heading_confidence",),
        migrations.RemoveField(model_name="vehicle", name="mmr_make",),
        migrations.RemoveField(model_name="vehicle", name="mmr_make_confidence",),
        migrations.RemoveField(model_name="vehicle", name="mmr_model",),
        migrations.RemoveField(model_name="vehicle", name="mmr_model_confidence",),
        migrations.RemoveField(model_name="vehicle", name="mmr_proctime",),
        migrations.RemoveField(model_name="vehicle", name="plate_chars",),
        migrations.RemoveField(model_name="vehicle", name="plate_country",),
        migrations.RemoveField(model_name="vehicle", name="plate_found",),
        migrations.RemoveField(model_name="vehicle", name="plate_roi",),
        migrations.RemoveField(model_name="vehicle", name="plate_type",),
        migrations.RemoveField(model_name="vehicle", name="plate_type_confidence",),
        migrations.RemoveField(model_name="vehicle", name="position_confidence",),
        migrations.RemoveField(model_name="vehicle", name="proctime",),
        migrations.RemoveField(model_name="vehicle", name="separated_text",),
        migrations.RemoveField(model_name="vehicle", name="unicode_text",),
    ]
